=== Getting your CV notice

Short & concise but make it stand out.

=== Extra activities (open source projects, hackathons, conferences, meetups etc)

Include the extra activities you do in addition to your job. These are all great for learning & network. Include open source projects, hackathons, conferences, meetups etc.

=== Covering letter

Should not include the same info on your CV. This should be concise & where you want to go & what benefits you can bring to the team & company.

=== Back your CV up with examples

Words on a CV only go so far. Back these up with links to examples. This could be from GitHub, Stackoverflow or even Twitter, you would be surprised the smallest bit of evidence will help.

=== Do your research

Check what companies you like. Corporate or Startup. Find where you will fit & enjoy.

=== Get some kind of experience

Even voluntary experience. Exposure to types of roles. You might not even be aware of roles that exist. New roles are created every single day.

Tip: Each month 36 new roles appear in tech alone.

=== Networking

It is not working the room, golf days. Its about trust & common interests. Be honest, sincere & listen. Dont forget to get details to continue the relationship.

=== Negotiation & Pay rise

Do negotiation & speak up. Make sure you can back up the reasons why.

=== Positive Language

If you havent done it before make it positive, for example: I havent done that but I am really interested to learn where & who can help me.

=== CV Size

3 pages should be long enough. Remember the person reading your CV probably has a pile of CVs to go through. Keep it concise.
