= CV Tips
By Eddie Jaoude
:toc:

:author:   Eddie Jaoude
:twitter:  https://twitter.com/eddiejaoude
:date:     2016
:version:  0.1.0
:repo:     https://github.com/eddiejaoude/book-cv-tips
:docinfo1:

[abstract]
== Abstract

This book are tips of DOs & DONT of CV.

[preface]
== Preface

Many people apply for the same role. How do you get your CV which is usually the first impression to stand out & make a good impression?

As with technology that keep on changing, this book will need continually updating, suggestions & pull requests are welcome. Currently on version v{version}.

Source Repository is on GitHub {repo}

<<<
== Introduction

With so many CVs passing the employers desk everyday, how do you stand out & grab their attention without including your life story? This is not a new question, it does however change with time. This tips book will list the DOs & DONTs of what to include in your CV.

TIP: This book will continually be updated, please check the version {version}. Any question please contact the author {author} on {twitter}.
